#!/bin/sh

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "^[^microservices;].+\.php$"`
for FILE in $FILES; do
 echo "It's not allowed to modify this file when using microservices: $FILE; only files inside microservices directory are allowed to be modified"
done
if [ ${#FILES[@]} -gt 0 ]; then
exit 1;
fi


make validate-composer insights-fix style-fix phpstan psalm test
git add .
