#!/bin/bash

FRAMEWORK_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$FRAMEWORK_DIR" ]]; then FRAMEWORK_DIR="$PWD"; fi

# shellcheck source=./frameworks/laravel
source "$FRAMEWORK_DIR/frameworks/laravel"

framework_select() {
    echo 'Please select framework to install: '
    PS3='Please enter your choice: '
    local options=("Laravel" "Quit")
    select opt in "${options[@]}"; do
        case $opt in
        "Laravel")
            laravel_make
            break
            ;;
        "Quit")
            exit 0
            ;;
        *) echo invalid option ;;
        esac
    done
}

framework_install_phpstan() {
    $"$(composer config extra.monorepo.framework)_install_phpstan"
}

framework_install_psalm() {
    $"$(composer config extra.monorepo.framework)_install_psalm"
}

framework_install_style_checker_fixer() {
    $"$(composer config extra.monorepo.framework)_install_style_checker_fixer"
}
