#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

# shellcheck source=./frameworks/laravel
source "$DIR/frameworks/laravel"

framework_select() {
    PS3='Please select framework to install: '
    local options=("Laravel" "Quit")
    select opt in "${options[@]}"; do
        case $opt in
        "Laravel")
            laravel_make
            break
            ;;
        "Quit")
            return
            ;;
        *) echo invalid option ;;
        esac
    done
}

framework_install_phpstan() {
    $"$(composer config extra.monorepo.framework)_install_phpstan"
}

framework_install_psalm() {
    $"$(composer config extra.monorepo.framework)_install_psalm"
}

framework_install_style_checker_fixer() {
    $"$(composer config extra.monorepo.framework)_install_style_checker_fixer"
}
